"""
Tests for betapy.core.io

Run with:  python -m pytest tests/
"""

import pytest
import tempfile
from pathlib import Path

from betapy.core.io import read_SPOSCAR, read_refpos, write_refpos


# Minimal SPOSCAR content for a 2-atom cell
SPOSCAR_CONTENT = """\
generated by phonopy
   1.0
     3.0000000   0.0000000   0.0000000
     0.0000000   3.0000000   0.0000000
     0.0000000   0.0000000   3.0000000
Li O
  1  1
Direct
  0.0000000   0.0000000   0.0000000
  0.5000000   0.5000000   0.5000000
"""


def write_temp(content, suffix=''):
    """Write content to a temp file and return its path."""
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix=suffix, delete=False)
    tmp.write(content)
    tmp.close()
    return tmp.name


def test_read_sposcar_basic():
    path = write_temp(SPOSCAR_CONTENT)
    data = read_SPOSCAR(path)
    assert data['chem_symbols'] == ['Li', 'O']
    assert data['chem_atoms'] == [1, 1]
    assert len(data['positions']) == 2
    assert data['lattice'][0] == pytest.approx([3.0, 0.0, 0.0])


def test_read_sposcar_positions():
    path = write_temp(SPOSCAR_CONTENT)
    data = read_SPOSCAR(path)
    assert data['positions'][0] == pytest.approx([0.0, 0.0, 0.0])
    assert data['positions'][1] == pytest.approx([0.5, 0.5, 0.5])


def test_write_read_refpos_roundtrip():
    positions = [[0.1, 0.2, 0.3], [0.7, 0.8, 0.9]]
    label = 'test_site'
    with tempfile.NamedTemporaryFile(suffix='', delete=False) as f:
        path = f.name
    write_refpos(label, positions, path)
    data = read_refpos(path)
    assert data['label'] == label
    assert data['num_sites'] == 2
    assert data['positions'][0] == pytest.approx([0.1, 0.2, 0.3])
    assert data['positions'][1] == pytest.approx([0.7, 0.8, 0.9])
